# Generated by Django 5.1.1 on 2024-09-11 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("species", models.CharField(max_length=255)),
                ("colour", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="MeowEntry",
        ),
    ]
